// ═══ 입시 조사 스냅샷 (고3 수능 정규반, 2026-08 조사) ═══
// 학생ID → 입시 응답. 출처: 김가경 국어 연구소 입시 조사 구글폼
window.ADMISSIONS = {
 "g3-8096": {
  "name": "신지환",
  "school": "산본고",
  "course": "S",
  "subject": "화작",
  "change": "그대로",
  "grade": "2",
  "susi": [
   "논술",
   "학종"
  ],
  "non": "1",
  "hak": "3",
  "gyo": "1",
  "top": "서울시립대",
  "bot": "한경국립대",
  "safe": "경북대",
  "weight": "1",
  "s6top": "정시 생각 안함(최저 맞춤)",
  "s6bot": "정시 생각 안함(최저 맞춤)",
  "s6safe": "정시 생각 안함(최저 맞춤)",
  "paid": "아니요",
  "intro": "",
  "schoolConsult": "네",
  "reason": "아직 내 차례가 되지 않음"
 },
 "g3-2054": {
  "name": "이연우",
  "school": "군포고",
  "course": "F",
  "subject": "화작",
  "change": "그대로",
  "grade": "3",
  "susi": [
   "학종",
   "교과"
  ],
  "non": "",
  "hak": "2",
  "gyo": "4",
  "top": "상명대",
  "bot": "경상국립대",
  "safe": "강원대·경상국립대·전북대",
  "weight": "2",
  "s6top": "경상국립대보다 하위(제주대·지방사립대 등)",
  "s6bot": "지방사립대학",
  "s6safe": "제주대",
  "paid": "아니요",
  "intro": "네",
  "schoolConsult": "네",
  "reason": ""
 },
 "g3-3445": {
  "name": "유희진",
  "school": "산본고",
  "course": "S",
  "subject": "화작",
  "change": "그대로",
  "grade": "3",
  "susi": [
   "학종",
   "교과"
  ],
  "non": "",
  "hak": "4",
  "gyo": "2",
  "top": "성신여대",
  "bot": "경북대",
  "safe": "경기대·한국공학대·경북대",
  "weight": "5",
  "s6top": "수원대",
  "s6bot": "강원대",
  "s6safe": "한경대",
  "paid": "아니요",
  "intro": "",
  "schoolConsult": "아니요",
  "reason": "아직 내 차례가 되지 않음"
 },
 "g3-6808": {
  "name": "양도윤",
  "school": "군포고",
  "course": "S",
  "subject": "언매",
  "change": "무계획",
  "grade": "2",
  "susi": [
   "논술",
   "학종",
   "교과"
  ],
  "non": "2",
  "hak": "2",
  "gyo": "2",
  "top": "성균관대",
  "bot": "가천대",
  "safe": "가천대",
  "weight": "9",
  "s6top": "국민대",
  "s6bot": "가천대",
  "s6safe": "숭실대",
  "paid": "아니요",
  "intro": "",
  "schoolConsult": "네",
  "reason": ""
 },
 "g3-4955": {
  "name": "김민주",
  "school": "군포고",
  "course": "S",
  "subject": "화작",
  "change": "그대로",
  "grade": "2",
  "susi": [
   "논술",
   "교과"
  ],
  "non": "5",
  "hak": "",
  "gyo": "1",
  "top": "성균관대",
  "bot": "서경대",
  "safe": "서울여대",
  "weight": "3",
  "s6top": "동국대",
  "s6bot": "숭실대",
  "s6safe": "광운대",
  "paid": "아니요",
  "intro": "",
  "schoolConsult": "네",
  "reason": ""
 },
 "g3-0891": {
  "name": "홍지안",
  "school": "부흥고",
  "course": "F",
  "subject": "언매",
  "change": "그대로",
  "grade": "2",
  "susi": [
   "논술",
   "학종"
  ],
  "non": "1",
  "hak": "5",
  "gyo": "",
  "top": "성균관대",
  "bot": "가톨릭대",
  "safe": "가톨릭대",
  "weight": "9",
  "s6top": "건국대",
  "s6bot": "국민대",
  "s6safe": "숭실대",
  "paid": "네",
  "intro": "네",
  "schoolConsult": "네",
  "reason": ""
 },
 "g3-2457": {
  "name": "공두영",
  "school": "산본고",
  "course": "S",
  "subject": "화작",
  "change": "그대로",
  "grade": "2",
  "susi": [
   "학종"
  ],
  "non": "",
  "hak": "5",
  "gyo": "1",
  "top": "성균관대",
  "bot": "동국대",
  "safe": "건국대",
  "weight": "5",
  "s6top": "모름(낮음)",
  "s6bot": "모름",
  "s6safe": "모름",
  "paid": "아니요",
  "intro": "",
  "schoolConsult": "네",
  "reason": ""
 },
 "g3-7069": {
  "name": "손환희",
  "school": "수원외고",
  "course": "F",
  "subject": "언매",
  "change": "그대로",
  "grade": "2",
  "susi": [
   "학종",
   "교과"
  ],
  "non": "",
  "hak": "4",
  "gyo": "1",
  "top": "가천대?·외대 글로벌?",
  "bot": "단국대(천안)",
  "safe": "단국대(천안)",
  "weight": "9",
  "s6top": "몰라요",
  "s6bot": "몰라요",
  "s6safe": "몰라요",
  "paid": "아니요",
  "intro": "",
  "schoolConsult": "네",
  "reason": ""
 },
 "g3-3534": {
  "name": "최재혁",
  "school": "흥진고",
  "course": "S",
  "subject": "화작",
  "change": "그대로",
  "grade": "1",
  "susi": [
   "학종",
   "교과"
  ],
  "non": "",
  "hak": "",
  "gyo": "",
  "top": "가천대",
  "bot": "경기대",
  "safe": "경기대",
  "weight": "10",
  "s6top": "충북대",
  "s6bot": "건국대",
  "s6safe": "중앙대",
  "paid": "아니요",
  "intro": "",
  "schoolConsult": "네",
  "reason": ""
 },
 "g3-2890": {
  "name": "김주아",
  "school": "수리고",
  "course": "S",
  "subject": "화작",
  "change": "그대로",
  "grade": "1",
  "susi": [
   "학종",
   "교과"
  ],
  "non": "",
  "hak": "3",
  "gyo": "3",
  "top": "서울대",
  "bot": "중앙대",
  "safe": "성균관대",
  "weight": "1",
  "s6top": "서울시립대",
  "s6bot": "홍익대",
  "s6safe": "건국대",
  "paid": "네",
  "intro": "",
  "schoolConsult": "네",
  "reason": ""
 },
 "g3-3621": {
  "name": "강지오",
  "school": "수리고",
  "course": "S",
  "subject": "언매",
  "change": "그대로",
  "grade": "3",
  "susi": [
   "논술"
  ],
  "non": "6",
  "hak": "",
  "gyo": "",
  "top": "국민대",
  "bot": "가천대",
  "safe": "경기대",
  "weight": "6",
  "s6top": "가천대",
  "s6bot": "한국공학대",
  "s6safe": "경기대",
  "paid": "아니요",
  "intro": "",
  "schoolConsult": "네",
  "reason": ""
 },
 "g3-4142": {
  "name": "최다온",
  "school": ".",
  "course": "F",
  "subject": "언매",
  "change": "그대로",
  "grade": "2·3",
  "susi": [
   "논술"
  ],
  "non": "6",
  "hak": "",
  "gyo": "",
  "top": "가톨릭대",
  "bot": "수원대",
  "safe": "수원대?",
  "weight": "3",
  "s6top": "가천대",
  "s6bot": "중부대",
  "s6safe": "신한대",
  "paid": "네",
  "intro": "네",
  "schoolConsult": "아니요",
  "reason": "학교에서 해주지 않음·아직 내 차례 아님·본인 원치 않음"
 },
 "g3-5730": {
  "name": "박세은",
  "school": "수리고",
  "course": "F",
  "subject": "언매",
  "change": "그대로",
  "grade": "1",
  "susi": [
   "논술"
  ],
  "non": "4",
  "hak": "2",
  "gyo": "",
  "top": "고려대",
  "bot": "서울시립대",
  "safe": "없음",
  "weight": "10",
  "s6top": "모르겠음",
  "s6bot": "모르겠음",
  "s6safe": "모르겠음",
  "paid": "아니요",
  "intro": "",
  "schoolConsult": "네",
  "reason": ""
 },
 "g3-01072212732": {
  "name": "박유미",
  "school": "초당고",
  "course": "F",
  "subject": "화작",
  "change": "그대로",
  "grade": "4",
  "susi": [
   "수시 지원 안 함"
  ],
  "non": "",
  "hak": "",
  "gyo": "",
  "top": "경기권 내 대학",
  "bot": "성적 안 나오면 대학 포기 고민",
  "safe": "모르겠음",
  "weight": "10",
  "s6top": "모르겠음",
  "s6bot": "모르겠음",
  "s6safe": "6평 미응시로 모름",
  "paid": "아니요",
  "intro": "네",
  "schoolConsult": "아니요",
  "reason": "본인 원치 않음"
 },
 "g3-8046": {
  "name": "김나연",
  "school": "수원외고",
  "course": "F",
  "subject": "언매",
  "change": "그대로",
  "grade": "1",
  "susi": [
   "학종"
  ],
  "non": "",
  "hak": "6",
  "gyo": "",
  "top": "고려대",
  "bot": "중앙대",
  "safe": "중앙대",
  "weight": "1",
  "s6top": "충북대",
  "s6bot": "충북대",
  "s6safe": "충북대",
  "paid": "아니요",
  "intro": "",
  "schoolConsult": "네",
  "reason": ""
 },
 "g3-01023308893": {
  "name": "오은빈",
  "school": "N수",
  "course": "F",
  "subject": "화작",
  "change": "그대로",
  "grade": "4",
  "susi": [
   "논술",
   "교과"
  ],
  "non": "5",
  "hak": "",
  "gyo": "1",
  "top": "중앙대 창의(논술)",
  "bot": "교과 라인 잡아야 함",
  "safe": "가톨릭대·광운대(논술 안정X)",
  "weight": "6",
  "s6top": "덕성여대(논술)",
  "s6bot": "모름",
  "s6safe": "수시 답변과 동일",
  "paid": "아니요",
  "intro": "",
  "schoolConsult": "아니요",
  "reason": "학교에서 해주지 않음"
 },
 "g3-2316": {
  "name": "윤영채",
  "school": "수리고",
  "course": "S",
  "subject": "화작",
  "change": "그대로",
  "grade": "3",
  "susi": [
   "논술",
   "학종"
  ],
  "non": "3",
  "hak": "3",
  "gyo": "",
  "top": "국민대",
  "bot": "한신대",
  "safe": "성결대",
  "weight": "6",
  "s6top": "안양대·한세대?",
  "s6bot": "잘 모르겠음",
  "s6safe": "평택대·성결대",
  "paid": "아니요",
  "intro": "",
  "schoolConsult": "네",
  "reason": ""
 },
 "g3-7795": {
  "name": "권오현",
  "school": "군포고",
  "course": "S",
  "subject": "언매",
  "change": "그대로",
  "grade": "3",
  "susi": [
   "논술"
  ],
  "non": "6",
  "hak": "",
  "gyo": "",
  "top": "건국대",
  "bot": "가천대",
  "safe": "가천대",
  "weight": "10",
  "s6top": "한국공학대",
  "s6bot": "대진대",
  "s6safe": "을지대",
  "paid": "네",
  "intro": "네",
  "schoolConsult": "아니요",
  "reason": "아직 내 차례가 되지 않음"
 },
 "g3-3145": {
  "name": "조은나래",
  "school": "군포고",
  "course": "S",
  "subject": "언매",
  "change": "9평 후 화작→언매",
  "grade": "2",
  "susi": [
   "학종"
  ],
  "non": "",
  "hak": "6",
  "gyo": "",
  "top": "한성대",
  "bot": "수원여대",
  "safe": "숭의여대·한양여대·수원여대",
  "weight": "8",
  "s6top": "서울 전문대?",
  "s6bot": "전문대",
  "s6safe": "정시 미확인",
  "paid": "네",
  "intro": "네",
  "schoolConsult": "아니요",
  "reason": "아직 내 차례가 되지 않음"
 },
 "g3-7299": {
  "name": "최현서",
  "school": "군포중앙고",
  "course": "S",
  "subject": "화작",
  "change": "그대로",
  "grade": "3",
  "susi": [
   "교과"
  ],
  "non": "",
  "hak": "3",
  "gyo": "3",
  "top": "중앙대",
  "bot": "가천대",
  "safe": "없음",
  "weight": "10",
  "s6top": "광운대",
  "s6bot": "성결대",
  "s6safe": "한국체육대",
  "paid": "아니요",
  "intro": "",
  "schoolConsult": "네",
  "reason": ""
 },
 "g3-3529": {
  "name": "성현혜",
  "school": "계원예고 졸",
  "course": "S",
  "subject": "언매",
  "change": "그대로",
  "grade": "1",
  "susi": [
   "수시 지원 안 함"
  ],
  "non": "",
  "hak": "",
  "gyo": "",
  "top": "서울대",
  "bot": "경희대·이대",
  "safe": "경희대·이대",
  "weight": "10",
  "s6top": "서울대?",
  "s6bot": "경희대",
  "s6safe": "경희대·이대",
  "paid": "아니요",
  "intro": "",
  "schoolConsult": "아니요",
  "reason": "본인 원치 않음"
 },
 "g3-1101": {
  "name": "신율",
  "school": "안산고",
  "course": "F",
  "subject": "언매",
  "change": "그대로",
  "grade": "2",
  "susi": [
   "학종"
  ],
  "non": "",
  "hak": "3",
  "gyo": "3",
  "top": "서성한?·중앙대?",
  "bot": "안정 교과 미정",
  "safe": "건동홍숙",
  "weight": "3",
  "s6top": "정시 미고려",
  "s6bot": "정시 미고려",
  "s6safe": "정시 미고려",
  "paid": "아니요",
  "intro": "",
  "schoolConsult": "네",
  "reason": ""
 },
 "g3-1880": {
  "name": "김보민",
  "school": "군포고",
  "course": "S",
  "subject": "언매",
  "change": "그대로",
  "grade": "3",
  "susi": [
   "학종",
   "교과"
  ],
  "non": "",
  "hak": "3",
  "gyo": "3",
  "top": "가천대",
  "bot": "전북대",
  "safe": "없음",
  "weight": "6",
  "s6top": "충북대",
  "s6bot": "성결대",
  "s6safe": "공주대",
  "paid": "아니요",
  "intro": "",
  "schoolConsult": "네",
  "reason": ""
 },
 "g3-1365": {
  "name": "이도경",
  "school": "우성고",
  "course": "S",
  "subject": "화작",
  "change": "그대로",
  "grade": "2",
  "susi": [
   "학종"
  ],
  "non": "2",
  "hak": "4",
  "gyo": "",
  "top": "국민대",
  "bot": "미정",
  "safe": "미정",
  "weight": "8",
  "s6top": "미확인",
  "s6bot": "미확인",
  "s6safe": "미확인",
  "paid": "네",
  "intro": "",
  "schoolConsult": "아니요",
  "reason": "아직 내 차례가 되지 않음"
 },
 "g3-2135": {
  "name": "김현지",
  "school": "수리고",
  "course": "S",
  "subject": "언매",
  "change": "그대로",
  "grade": "2·3",
  "susi": [
   "논술",
   "학종"
  ],
  "non": "4",
  "hak": "2",
  "gyo": "",
  "top": "중앙대",
  "bot": "가천대·경기대?",
  "safe": "안양대·성결대",
  "weight": "9",
  "s6top": "건국대 글로컬(진학사 위험)",
  "s6bot": "국립목포해양대 생명공학(안정)",
  "s6safe": "건양대 제약생명공학(적정)",
  "paid": "",
  "intro": "",
  "schoolConsult": "네",
  "reason": ""
 },
 "g3-9080": {
  "name": "강예담",
  "school": "청심국제고",
  "course": "F",
  "subject": "언매",
  "change": "그대로",
  "grade": "1",
  "susi": [
   "학종"
  ],
  "non": "6",
  "hak": "6",
  "gyo": "",
  "top": "아주대(의대)·가천대(의대)",
  "bot": "성균관대",
  "safe": "연세대",
  "weight": "1",
  "s6top": "잘 몰라요",
  "s6bot": "잘 몰라요",
  "s6safe": "잘 몰라요",
  "paid": "아니요",
  "intro": "",
  "schoolConsult": "네",
  "reason": ""
 },
 "g3-3367": {
  "name": "신지효",
  "school": "안양예고",
  "course": "S",
  "subject": "언매",
  "change": "9평 후 언매→화작",
  "grade": "3",
  "susi": [
   "교과"
  ],
  "non": "2",
  "hak": "",
  "gyo": "",
  "top": "경희대",
  "bot": "동국대",
  "safe": "서울여대",
  "weight": "8",
  "s6top": "경희대",
  "s6bot": "추계예대",
  "s6safe": "상명대",
  "paid": "",
  "intro": "",
  "schoolConsult": "네",
  "reason": ""
 }
};
